import sys
from pathlib import Path
import numpy as np
import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [
    str(ROOT),
    str(ROOT / "detector"),
    str(ROOT / "detector" / "core" / "datasets"),
    str(ROOT / "tools" / "dataset_converter"),
]

from tools.dataset_converter.create_gt_database import (
    extract_object_points,
    build_kitti_gt_database,
)


def test_extract_object_points_bottom_convention():
    # Box bottom center at (10, 0, -1.0), h=2.0 (spans z from -1.0 to 1.0)
    # 7-col box: [h, w, l, x, y, z, yaw]
    box = np.array([2.0, 2.0, 4.0, 10.0, 0.0, -1.0, 0.0], dtype=np.float32)
    points = np.array(
        [
            [10.0, 0.0, -0.5, 0.8],  # Inside (z = -0.5 is between -1.0 and 1.0)
            [11.0, 0.5, 0.5, 0.6],  # Inside
            [10.0, 0.0, 1.5, 0.9],  # Above top (z = 1.5 > 1.0) -> Outside
            [10.0, 0.0, -1.5, 0.2],  # Below bottom (z = -1.5 < -1.0) -> Outside
            [15.0, 0.0, 0.0, 0.9],  # Outside in x
        ],
        dtype=np.float32,
    )

    inside_pts = extract_object_points(points, box)
    assert len(inside_pts) == 2
    assert np.allclose(inside_pts[0, :3], [10.0, 0.0, -0.5])
    assert np.allclose(inside_pts[1, :3], [11.0, 0.5, 0.5])


def test_extract_object_points_8col():
    # 8-col box: [cls, h, w, l, x, y, z, yaw]
    box_8 = np.array(
        [0.0, 2.0, 2.0, 4.0, 10.0, 0.0, -1.0, 0.0], dtype=np.float32
    )
    points = np.array([[10.0, 0.0, -0.5, 0.8]], dtype=np.float32)
    inside_pts = extract_object_points(points, box_8)
    assert len(inside_pts) == 1


def test_build_kitti_gt_database_mock(tmp_path):
    import pickle

    # Create mock KITTI directory structure
    processed_dir = tmp_path / "processed"
    pointcloud_dir = processed_dir / "training" / "pointcloud"
    label_dir = processed_dir / "training" / "label"
    pointcloud_dir.mkdir(parents=True)
    label_dir.mkdir(parents=True)

    # Mock file 000001
    sample_id = "000001"
    # Points with 10 inside car box
    car_pts = np.zeros((10, 4), dtype=np.float32)
    car_pts[:, 0] = np.linspace(9.0, 11.0, 10)  # around x=10
    car_pts[:, 1] = np.linspace(-0.5, 0.5, 10)  # around y=0
    car_pts[:, 2] = np.linspace(-1.0, 0.5, 10)  # z in [-1, 0.5]
    car_pts[:, 3] = 0.5
    car_pts.tofile(str(pointcloud_dir / f"{sample_id}.bin"))

    # Label: Car h w l x y z yaw
    label_content = "Car 1.5 1.8 4.5 10.0 0.0 -1.0 0.0\n"
    (label_dir / f"{sample_id}.txt").write_text(
        label_content, encoding="utf-8"
    )

    train_ids_file = tmp_path / "train.txt"
    train_ids_file.write_text(f"{sample_id}\n", encoding="utf-8")

    out_pkl = tmp_path / "gt_database.pkl"
    build_kitti_gt_database(
        str(processed_dir), str(train_ids_file), str(out_pkl), min_points=5
    )

    assert out_pkl.exists()
    with open(out_pkl, "rb") as f:
        db = pickle.load(f)

    assert "Car" in db
    assert len(db["Car"]) == 1
    sample = db["Car"][0]
    assert sample["num_points"] == 10
    assert sample["box"].shape == (8,)
    assert np.isclose(sample["r_origin"], 10.0)


def test_build_kitti_gt_database_canonical_yaw_rotation(tmp_path):
    import pickle

    processed_dir = tmp_path / "processed"
    pointcloud_dir = processed_dir / "training" / "pointcloud"
    label_dir = processed_dir / "training" / "label"
    pointcloud_dir.mkdir(parents=True)
    label_dir.mkdir(parents=True)

    sample_id = "000002"
    # Car oriented at yaw = pi/2 (heading along +Y)
    # Box: h=2.0, w=2.0, l=4.0, x=10.0, y=0.0, z=-1.0, yaw=pi/2
    # In sensor frame, length 4.0 is along Y, width 2.0 is along X.
    pts = np.zeros((10, 4), dtype=np.float32)
    pts[:, 0] = 10.0  # Center of width
    pts[:, 1] = np.linspace(-1.5, 1.5, 10)  # Along length (in Y)
    pts[:, 2] = -0.5
    pts[:, 3] = 0.8
    pts.tofile(str(pointcloud_dir / f"{sample_id}.bin"))

    label_content = f"Car 2.0 2.0 4.0 10.0 0.0 -1.0 {np.pi/2:.6f}\n"
    (label_dir / f"{sample_id}.txt").write_text(label_content, encoding="utf-8")

    train_ids_file = tmp_path / "train.txt"
    train_ids_file.write_text(f"{sample_id}\n", encoding="utf-8")

    out_pkl = tmp_path / "gt_database.pkl"
    build_kitti_gt_database(
        str(processed_dir), str(train_ids_file), str(out_pkl), min_points=5
    )

    with open(out_pkl, "rb") as f:
        db = pickle.load(f)

    sample = db["Car"][0]
    can_pts = sample["points"]
    # In canonical frame (heading along +X), length 4.0 must be along X, width along Y!
    assert np.all(np.abs(can_pts[:, 0]) <= 2.0)  # l / 2 = 2.0
    assert np.all(np.abs(can_pts[:, 1]) <= 1.0)  # w / 2 = 1.0
    # The spread along X must be > 2.0 and along Y must be ~0
    assert np.ptp(can_pts[:, 0]) > 2.0
    assert np.ptp(can_pts[:, 1]) < 0.1


def test_build_kitti_gt_database_direct_layout_and_manifest_tags(tmp_path):
    import pickle

    # Direct layout as generated by prepare_kitti.py:
    # processed/pointcloud/{id}.bin and processed/label/{id}.txt (no "training" subfolder)
    processed_dir = tmp_path / "processed"
    pointcloud_dir = processed_dir / "pointcloud"
    label_dir = processed_dir / "label"
    pointcloud_dir.mkdir(parents=True)
    label_dir.mkdir(parents=True)

    sample_id = "000003"
    pts = np.zeros((10, 4), dtype=np.float32)
    pts[:, 0] = np.linspace(9.0, 11.0, 10)
    pts[:, 1] = np.linspace(-0.5, 0.5, 10)
    pts[:, 2] = np.linspace(-1.0, 0.5, 10)
    pts[:, 3] = 0.5
    pts.tofile(str(pointcloud_dir / f"{sample_id}.bin"))

    label_content = "Car 1.5 1.8 4.5 10.0 0.0 -1.0 0.0\n"
    (label_dir / f"{sample_id}.txt").write_text(label_content, encoding="utf-8")

    # Manifest with dataset tag ";kitti"
    train_ids_file = tmp_path / "train.txt"
    train_ids_file.write_text(f"{sample_id};kitti\n", encoding="utf-8")

    out_pkl = tmp_path / "gt_database.pkl"
    build_kitti_gt_database(
        str(processed_dir), str(train_ids_file), str(out_pkl), min_points=5
    )

    assert out_pkl.exists()
    with open(out_pkl, "rb") as f:
        db = pickle.load(f)

    assert "Car" in db
    assert len(db["Car"]) == 1
    assert db["Car"][0]["num_points"] == 10


def _write_builder_frame(tmp_path, *, num_points=5, label="Car 2 2 4 10 0 -1 0\n"):
    processed_dir = tmp_path / "processed"
    pointcloud_dir = processed_dir / "pointcloud"
    label_dir = processed_dir / "label"
    pointcloud_dir.mkdir(parents=True)
    label_dir.mkdir(parents=True)
    points = np.tile(np.array([10, 0, 0, 0.5], dtype=np.float32), (num_points, 1))
    points.tofile(pointcloud_dir / "000001.bin")
    (label_dir / "000001.txt").write_text(label, encoding="utf-8")
    train_ids_file = tmp_path / "train.txt"
    train_ids_file.write_text("000001;kitti\n", encoding="utf-8")
    return processed_dir, train_ids_file


def test_builder_accepts_bare_output_filename(tmp_path, monkeypatch):
    import pickle

    processed_dir, train_ids_file = _write_builder_frame(tmp_path)
    monkeypatch.chdir(tmp_path)
    build_kitti_gt_database(str(processed_dir), str(train_ids_file), "database.pkl")

    with open("database.pkl", "rb") as f:
        database = pickle.load(f)
    assert set(database) == {"Car", "Pedestrian", "Cyclist"}
    assert len(database["Car"]) == 1
    assert database["Car"][0]["num_points"] == 5


@pytest.mark.parametrize("missing_part", ["pointcloud", "label", "both"])
def test_builder_rejects_all_missing_frames_with_stats(tmp_path, missing_part):
    processed_dir, train_ids_file = _write_builder_frame(tmp_path)
    if missing_part in ("pointcloud", "both"):
        (processed_dir / "pointcloud" / "000001.bin").unlink()
    if missing_part in ("label", "both"):
        (processed_dir / "label" / "000001.txt").unlink()
    output_file = tmp_path / "new_output" / "database.pkl"

    with pytest.raises(ValueError, match="No GT objects extracted") as exc:
        build_kitti_gt_database(str(processed_dir), str(train_ids_file), str(output_file))

    message = str(exc.value)
    assert "frames_requested=1" in message
    assert "frames_processed=0" in message
    assert "frames_missing=1" in message
    assert "objects_extracted=0" in message
    assert str(train_ids_file) in message
    assert not output_file.parent.exists()


@pytest.mark.parametrize(
    ("num_points", "label", "candidate_objects", "objects_below_min_points"),
    [
        (4, "Car 2 2 4 10 0 -1 0\n", 1, 1),
        (0, "Car 2 2 4 10 0 -1 0\n", 1, 1),
        (5, "DontCare 2 2 4 10 0 -1 0\n", 0, 0),
        (5, "", 0, 0),
    ],
)
def test_builder_rejects_no_samples_without_overwriting_output(
    tmp_path, num_points, label, candidate_objects, objects_below_min_points
):
    processed_dir, train_ids_file = _write_builder_frame(
        tmp_path, num_points=num_points, label=label
    )
    output_file = tmp_path / "database.pkl"
    output_file.write_bytes(b"existing database")

    with pytest.raises(ValueError, match="No GT objects extracted") as exc:
        build_kitti_gt_database(str(processed_dir), str(train_ids_file), str(output_file))

    message = str(exc.value)
    assert "frames_requested=1" in message
    assert "frames_processed=1" in message
    assert "frames_missing=0" in message
    assert f"candidate_objects={candidate_objects}" in message
    assert f"objects_below_min_points={objects_below_min_points}" in message
    assert "objects_extracted=0" in message
    assert "min_points=5" in message
    assert output_file.read_bytes() == b"existing database"


def test_builder_rejects_empty_manifest_with_stats(tmp_path):
    processed_dir, train_ids_file = _write_builder_frame(tmp_path)
    train_ids_file.write_text("\n  \n;kitti\n", encoding="utf-8")
    output_file = tmp_path / "database.pkl"

    with pytest.raises(ValueError, match="No GT objects extracted") as exc:
        build_kitti_gt_database(str(processed_dir), str(train_ids_file), str(output_file))

    assert "frames_requested=0" in str(exc.value)
    assert "frames_processed=0" in str(exc.value)
    assert "frames_missing=0" in str(exc.value)
    assert not output_file.exists()


def test_builder_keeps_valid_samples_when_other_frames_are_missing(tmp_path, capsys):
    import pickle

    processed_dir, train_ids_file = _write_builder_frame(tmp_path)
    train_ids_file.write_text("000001;kitti\n000002;kitti\n", encoding="utf-8")
    output_file = tmp_path / "new_output" / "database.pkl"

    build_kitti_gt_database(str(processed_dir), str(train_ids_file), str(output_file))

    with output_file.open("rb") as f:
        database = pickle.load(f)
    assert len(database["Car"]) == 1
    assert "Processed 1/2 frames" in capsys.readouterr().out


@pytest.mark.parametrize("min_points", [0, -1, 1.5, True])
def test_builder_rejects_invalid_min_points(tmp_path, min_points):
    processed_dir, train_ids_file = _write_builder_frame(tmp_path, num_points=0)
    output_file = tmp_path / "database.pkl"

    with pytest.raises(ValueError, match="min_points must be a positive integer"):
        build_kitti_gt_database(
            str(processed_dir), str(train_ids_file), str(output_file), min_points=min_points
        )

    assert not output_file.exists()
